export const VIDEOS_LIST = "VIDEOS_LIST";
export const VIDEOS_SEARCH_ITEM = "VIDEOS_SEARCH_ITEM";
export const VIDEOS_PAGE_TOKEN = "VIDEOS_PAGE_TOKEN";
export const VIDEOS_CONTENT_DETAIL = "VIDEOS_CONTENT_DETAIL";
export const CLEAR_VIDEOS_CONTENT_DETAIL = "CLEAR_VIDEOS_CONTENT_DETAIL";
export const GET_LOCAL_STORAGE_ID = "GET_LOCAL_STORAGE_ID";
export const UPDATE_LOCAL_STORAGE_ID = "UPDATE_LOCAL_STORAGE_ID";
export const DELETE_LOCAL_STORAGE_ID = "DELETE_LOCAL_STORAGE_ID";
